In [2]:
import pandas as pd

In [3]:
df=pd.read_csv("data3.csv")

In [4]:
df

      Actor     Film  Year of Release    Genre  Box Office ($M)  IMDb Rating
0   Actor A  Movie A             2011   Sci-Fi           938.66          8.9
1   Actor B  Movie B             2022    Drama           432.50          5.8
2   Actor C  Movie C             2009   Sci-Fi           724.39          6.0
3   Actor D  Movie D             1998   Action           992.40          7.1
4   Actor E  Movie E             2018   Horror           176.42          8.3
5   Actor F  Movie F             1997  Fantasy           100.42          5.2
6   Actor G  Movie G             1992  Fantasy           862.33          7.7
7   Actor H  Movie H             2019   Sci-Fi           138.17          5.3
8   Actor I  Movie I             2023   Horror           234.53          7.7
9   Actor J  Movie J             2021   Action           656.59          6.9
10  Actor K  Movie K             2012   Sci-Fi           180.05          6.0
11  Actor L  Movie L             2017    Drama           727.51          9.4
12  Actor M  Movie M             2015   Sci-Fi           282.73          6.0
13  Actor N  Movie N             2014    Drama           779.62          8.8
14  Actor O  Movie O             2010  Fantasy           980.96          6.3